version: 2
jobs:
  build:
    working_directory: ~/ghc
    docker:
    - image: haskell:8
    steps:
    - run:
        name: git
        command: |
          apt-get update
          apt-get install -y git openssh-client
    - checkout
    - run:
        name: build
        command: |
          # do  not build docs
          echo 'HADDOCK_DOCS       = NO' >> mk/validate.mk
          echo 'BUILD_SPHINX_HTML  = NO' >> mk/validate.mk
          echo 'BUILD_SPHINX_PDF   = NO' >> mk/validate.mk
          # do not build dynamic libraries
          echo 'DYNAMIC_GHC_PROGRAMS = NO' >> mk/validate.mk
          echo 'GhcLibWays = v' >> mk/validate.mk
          nproc
          THREADS=2 SKIP_PERF_TESTS=YES VERBOSE=2 ./validate --fast --quiet
          
